apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: slack-users
  description: |
    Automate slack users removal
  annotations:
    github.com/project-slug: realexcel2021/backstage-demo
    backstage.io/source-template: template:default/send-slack-message

spec:
  type: service
  lifecycle: experimental
  owner: team-a
