apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: send-slack-message
  title: Send Message Using Slack API
  description: This template sends slack message using the api
spec:
  owner: user:guest
  type: service


  parameters:
    - title: API token
      properties:
        team_id:
          title: Team ID
          type: string
        user_id:
          title: User ID
          type: string

  steps:
    - id: 'remove-user'
      name: 'Remove Slack User'
      action: 'http:backstage:request'
      input:
        method: 'POST'
        path: 'proxy/slack/admin.users.remove'
        headers:
          content-type: 'application/json'
        body:
          team_id: ${{ parameters.team_id }}
          user_id: ${{ parameters.user_id }}

    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/realexcel2021/backstage-demo

    - id: append-file
      name: Append To File Or Create New
      action: roadiehq:utils:fs:append
      input:
        path: users.txt
        content: ${{ parameters.user_id }}

    - id: publish-pr
      name: Publish PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=backstage-demo&owner=realexcel2021
        branchName:  main
        title: Pull Request to remove user ${{ parameters.user_id }}
        description: PR created from Backstage to remove slack user

  outputs:
    text:
    - title: Operation Completed
      content: |
        User  `${{ parameters.user_id }}` successfully removed!!
